version: '3.3'

services:
  keycloak:
    container_name: keycloak
    build: .
    image: keycloak:16.1.1-latest
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
